# -*- coding: utf-8 -*-
"""brain_hod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBgunjxGz-nSq10NYGX654EprauB8rcf
"""

from google.colab import drive
drive.mount('/content/drive')

import os

train_path = "/content/drive/MyDrive/BrainTumorDataset/Training"
test_path = "/content/drive/MyDrive/BrainTumorDataset/Testing"

print("Training Exists:", os.path.exists(train_path))
print("Testing Exists:", os.path.exists(test_path))

TRAIN_DIR = "/content/drive/MyDrive/BrainTumorDataset/Training"

TEST_DIR = "/content/drive/MyDrive/BrainTumorDataset/Testing"

# ==================================================
# MEDVISION AI
# Brain MRI Tumor Detection
# PART 1 - Imports
# ==================================================

import os
import numpy as np
import matplotlib.pyplot as plt

import torch
from torchvision import datasets
from torchvision import transforms
from torch.utils.data import DataLoader

print("PyTorch Version :", torch.__version__)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :", device)

# ==================================================
# Dataset Paths
# ==================================================

TRAIN_DIR = "/content/drive/MyDrive/BrainTumorDataset/Training"
TEST_DIR  = "/content/drive/MyDrive/BrainTumorDataset/Testing"

print(TRAIN_DIR)
print(TEST_DIR)

# ==================================================
# Dataset Paths
# ==================================================

TRAIN_DIR = "/content/drive/MyDrive/BrainTumorDataset/Training"
TEST_DIR  = "/content/drive/MyDrive/BrainTumorDataset/Testing"

print(TRAIN_DIR)
print(TEST_DIR)

# ==================================================
# Image Configuration
# ==================================================

IMAGE_SIZE = 224
BATCH_SIZE = 32

print("Image Size :", IMAGE_SIZE)
print("Batch Size :", BATCH_SIZE)

# ==================================================
# Training Transformations
# ==================================================

train_transforms = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.RandomHorizontalFlip(p=0.5),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

# ==================================================
# Testing Transformations
# ==================================================

test_transforms = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

print("Transforms Created Successfully")

# ==================================================
# Load Datasets
# ==================================================

train_dataset = datasets.ImageFolder(
    root=TRAIN_DIR,
    transform=train_transforms
)

test_dataset = datasets.ImageFolder(
    root=TEST_DIR,
    transform=test_transforms
)

print("Training Images :", len(train_dataset))
print("Testing Images  :", len(test_dataset))

# ==================================================
# Class Names
# ==================================================

class_names = train_dataset.classes

print("Classes Found:\n")

for idx, name in enumerate(class_names):

    print(f"{idx} --> {name}")

# ==================================================
# DataLoaders
# ==================================================

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

print("DataLoaders Created Successfully")

# ==================================================
# Verify Shapes
# ==================================================

images, labels = next(iter(train_loader))

print("Images Shape :", images.shape)
print("Labels Shape :", labels.shape)

# ==================================================
# Visualize MRI Images
# ==================================================

def show_batch():

    images, labels = next(iter(train_loader))

    plt.figure(figsize=(14,8))

    for i in range(8):

        plt.subplot(2,4,i+1)

        img = images[i].numpy().transpose(1,2,0)

        mean = np.array([0.485,0.456,0.406])
        std = np.array([0.229,0.224,0.225])

        img = std * img + mean
        img = np.clip(img,0,1)

        plt.imshow(img)

        plt.title(class_names[labels[i]])

        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_batch()

!pip install torchinfo -q

from torchvision import models
from torchinfo import summary

import torch.nn as nn
import torch.optim as optim

# ==================================================
# Load EfficientNet-B0
# ==================================================

model = models.efficientnet_b0(
    weights=models.EfficientNet_B0_Weights.DEFAULT
)

print("Pretrained EfficientNet Loaded")

# ==================================================
# Replace Classifier Head
# ==================================================

num_features = model.classifier[1].in_features

print("Input Features:", num_features)

model.classifier = nn.Sequential(

    nn.Dropout(0.3),

    nn.Linear(
        num_features,
        4
    )
)

print(model.classifier)

model = model.to(device)

print("Model moved to:", device)

# ==================================================
# Loss Function
# ==================================================

criterion = nn.CrossEntropyLoss()

print("Loss Function Created")

optimizer = optim.AdamW(
    model.parameters(),
    lr=0.0001,
    weight_decay=1e-4
)

print("Optimizer Created")

scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='max',
    factor=0.5,
    patience=2
)

print("Scheduler Created")

# ==================================================
# Test Forward Pass
# ==================================================

sample_batch, _ = next(iter(train_loader))

sample_batch = sample_batch.to(device)

with torch.no_grad():

    outputs = model(sample_batch)

print("Output Shape:", outputs.shape)

summary(
    model,
    input_size=(1,3,224,224)
)

# ==================================================
# Training Configuration
# ==================================================

EPOCHS = 15

best_accuracy = 0.0

train_losses = []
val_losses = []

train_accuracies = []
val_accuracies = []

print("Training Configuration Ready")

# ==================================================
# Training Function
# ==================================================

def train_one_epoch(model,
                    loader,
                    criterion,
                    optimizer,
                    device):

    model.train()

    running_loss = 0.0

    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(loader)

    epoch_accuracy = 100 * correct / total

    return epoch_loss, epoch_accuracy

# ==================================================
# Validation Function
# ==================================================

def validate(model,
             loader,
             criterion,
             device):

    model.eval()

    running_loss = 0.0

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(loader)

    epoch_accuracy = 100 * correct / total

    return epoch_loss, epoch_accuracy

# ==================================================
# Main Training Loop
# ==================================================

for epoch in range(EPOCHS):

    train_loss, train_acc = train_one_epoch(
        model,
        train_loader,
        criterion,
        optimizer,
        device
    )

    val_loss, val_acc = validate(
        model,
        test_loader,
        criterion,
        device
    )

    scheduler.step(val_acc)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(
        f"Epoch [{epoch+1}/{EPOCHS}] | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Acc: {train_acc:.2f}% | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_acc:.2f}%"
    )

    if val_acc > best_accuracy:

        best_accuracy = val_acc

        torch.save(
            model.state_dict(),
            "best_brain_model.pth"
        )

        print(
            f"Best Model Saved "
            f"(Accuracy = {best_accuracy:.2f}%)"
        )

import os

print(
    "Model Saved:",
    os.path.exists("best_brain_model.pth")
)

!pip install seaborn scikit-learn -q

import seaborn as sns

from sklearn.metrics import (
    confusion_matrix,
    classification_report
)

import pandas as pd

# ==========================================
# Load Best Model
# ==========================================

best_model = models.efficientnet_b0(
    weights=None
)

best_model.classifier = nn.Sequential(
    nn.Dropout(0.3),
    nn.Linear(1280,4)
)

best_model.load_state_dict(
    torch.load(
        "best_brain_model.pth",
        map_location=device
    )
)

best_model.to(device)

best_model.eval()

print("Best Model Loaded Successfully")

plt.figure(figsize=(10,5))

plt.plot(
    train_accuracies,
    label="Train Accuracy"
)

plt.plot(
    val_accuracies,
    label="Validation Accuracy"
)

plt.title("Accuracy Curve")

plt.xlabel("Epoch")

plt.ylabel("Accuracy (%)")

plt.legend()

plt.grid()

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    train_losses,
    label="Train Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.title("Loss Curve")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.grid()

plt.show()

# ==========================================
# Collect Predictions
# ==========================================

y_true = []
y_pred = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = best_model(images)

        _, predicted = torch.max(outputs,1)

        y_true.extend(labels.numpy())

        y_pred.extend(
            predicted.cpu().numpy()
        )

print("Prediction Collection Complete")

cm = confusion_matrix(
    y_true,
    y_pred
)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Brain MRI Confusion Matrix")

plt.show()

report = classification_report(
    y_true,
    y_pred,
    target_names=class_names
)

print(report)

torch.save({
    'model_state_dict': model.state_dict(),
    'class_names': class_names,
    'image_size': IMAGE_SIZE
}, 'brain_model_complete.pth')

print("Complete model file saved")

import os

print(os.path.exists("brain_model_complete.pth"))

!pip install grad-cam -q

import cv2
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

# ==========================================
# Rebuild EfficientNet Architecture
# ==========================================

from torchvision import models
import torch.nn as nn

gradcam_model = models.efficientnet_b0(weights=None)

gradcam_model.classifier = nn.Sequential(
    nn.Dropout(0.3),
    nn.Linear(1280, 4)
)

checkpoint = torch.load(
    "brain_model_complete.pth",
    map_location=device
)

gradcam_model.load_state_dict(
    checkpoint["model_state_dict"]
)

gradcam_model.to(device)
gradcam_model.eval()

print("GradCAM Model Loaded")

# ==========================================
# Final Convolution Layer
# ==========================================

target_layers = [gradcam_model.features[-1]]

print(target_layers)

from google.colab import files

uploaded = files.upload()

# ==========================================
# Get Uploaded Filename
# ==========================================

image_path = list(uploaded.keys())[0]

print(image_path)

# ==========================================
# Image Preprocessing
# ==========================================

image = Image.open(image_path).convert("RGB")

display_image = image.copy()

image = image.resize((224,224))

image_np = np.array(image)

rgb_img = image_np.astype(np.float32) / 255.0

input_tensor = test_transforms(image).unsqueeze(0)

input_tensor = input_tensor.to(device)

print(input_tensor.shape)

# ==========================================
# Prediction
# ==========================================

with torch.no_grad():

    outputs = gradcam_model(input_tensor)

    probabilities = torch.softmax(
        outputs,
        dim=1
    )

    confidence, predicted_class = torch.max(
        probabilities,
        dim=1
    )

pred_idx = predicted_class.item()

pred_label = class_names[pred_idx]

conf = confidence.item() * 100

print("Prediction :", pred_label)
print("Confidence :", round(conf,2), "%")

# ==========================================
# GradCAM
# ==========================================

cam = GradCAM(
    model=gradcam_model,
    target_layers=target_layers
)

targets = [
    ClassifierOutputTarget(pred_idx)
]

grayscale_cam = cam(
    input_tensor=input_tensor,
    targets=targets
)

grayscale_cam = grayscale_cam[0]

# ==========================================
# Overlay Heatmap
# ==========================================

visualization = show_cam_on_image(
    rgb_img,
    grayscale_cam,
    use_rgb=True
)

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(display_image)
plt.title("Original MRI")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(grayscale_cam, cmap="jet")
plt.title("GradCAM Heatmap")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(visualization)
plt.title("Overlay")
plt.axis("off")

plt.tight_layout()
plt.show()

# ==========================================
# Load Metadata
# ==========================================

checkpoint = torch.load(
    "brain_model_complete.pth",
    map_location=device
)

class_names = checkpoint["class_names"]

print(class_names)

# ==========================================
# Prediction Function
# ==========================================

def predict_mri(image_path):

    image = Image.open(image_path).convert("RGB")

    image = image.resize((224,224))

    input_tensor = test_transforms(image)

    input_tensor = input_tensor.unsqueeze(0)

    input_tensor = input_tensor.to(device)

    with torch.no_grad():

        outputs = gradcam_model(input_tensor)

        probabilities = torch.softmax(
            outputs,
            dim=1
        )[0]

    pred_idx = torch.argmax(
        probabilities
    ).item()

    pred_class = class_names[pred_idx]

    confidence = (
        probabilities[pred_idx].item() * 100
    )

    all_probs = {}

    for idx, class_name in enumerate(class_names):

        all_probs[class_name] = round(
            probabilities[idx].item() * 100,
            2
        )

    return (
        pred_class,
        confidence,
        all_probs
    )

image_path = "/content/33.jpg"

prediction, confidence, probs = predict_mri(image_path)

print("Prediction:", prediction)

print("Confidence:", round(confidence,2), "%")

print("\nClass Probabilities:\n")

for k, v in probs.items():

    print(f"{k}: {v}%")

# ==========================================
# Probability Display Function
# ==========================================

def show_probabilities(probs):

    plt.figure(figsize=(8,4))

    plt.bar(
        probs.keys(),
        probs.values()
    )

    plt.ylabel("Confidence (%)")

    plt.title("Brain MRI Classification Scores")

    plt.show()

show_probabilities(probs)

# ==================================================
# Smart Clinical Report Generator
# ==================================================

def generate_report(prediction, confidence):

    confidence = round(confidence, 2)

    if prediction == "glioma":

        findings = (
            "MRI brain demonstrates imaging features "
            "suggestive of glioma."
        )

        impression = (
            f"Glioma detected with "
            f"{confidence}% confidence."
        )

        recommendation = (
            "Recommend neurology/neurosurgery consultation. "
            "Clinical correlation and further review advised."
        )

    elif prediction == "meningioma":

        findings = (
            "MRI brain demonstrates imaging features "
            "suggestive of meningioma."
        )

        impression = (
            f"Meningioma detected with "
            f"{confidence}% confidence."
        )

        recommendation = (
            "Recommend specialist evaluation and "
            "radiological correlation."
        )

    elif prediction == "pituitary":

        findings = (
            "MRI brain demonstrates imaging features "
            "suggestive of pituitary tumor."
        )

        impression = (
            f"Pituitary tumor detected with "
            f"{confidence}% confidence."
        )

        recommendation = (
            "Endocrinology and neurosurgical consultation "
            "may be considered."
        )

    else:

        findings = (
            "No significant imaging evidence of "
            "intracranial tumor identified."
        )

        impression = (
            f"No tumor detected with "
            f"{confidence}% confidence."
        )

        recommendation = (
            "Routine follow-up and clinical correlation "
            "recommended if symptoms persist."
        )

    report = f"""
==================================================
MEDVISION AI - BRAIN MRI ANALYSIS REPORT
==================================================

Findings:
{findings}

Impression:
{impression}

Recommendation:
{recommendation}

--------------------------------------------------
AI Generated Research Prototype Report
Not Intended For Clinical Diagnosis
--------------------------------------------------
"""

    return report

report = generate_report(
    prediction,
    confidence
)

print(report)

# ==================================================
# Complete Brain MRI Analysis
# ==================================================

def analyze_mri(image_path):

    prediction, confidence, probs = predict_mri(
        image_path
    )

    report = generate_report(
        prediction,
        confidence
    )

    return {
        "prediction": prediction,
        "confidence": confidence,
        "probabilities": probs,
        "report": report
    }

result = analyze_mri(image_path)

print("Prediction:")
print(result["prediction"])

print("\nConfidence:")
print(round(result["confidence"],2))

print("\nReport:")
print(result["report"])

def confidence_level(conf):

    if conf >= 95:
        return "Very High"

    elif conf >= 85:
        return "High"

    elif conf >= 70:
        return "Moderate"

    else:
        return "Low"

print(
    confidence_level(confidence)
)

!pip install reportlab -q

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

from datetime import datetime

# ==================================================
# MedVision AI PDF Report Generator
# ==================================================

def create_pdf_report(
    prediction,
    confidence,
    report_text,
    filename="Brain_MRI_Report.pdf"
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # ==========================================
    # Title
    # ==========================================

    title = Paragraph(
        "<b>MEDVISION AI</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(
        Spacer(1,12)
    )

    subtitle = Paragraph(
        "<b>Brain MRI Analysis Report</b>",
        styles["Heading2"]
    )

    elements.append(subtitle)

    elements.append(
        Spacer(1,20)
    )

    # ==========================================
    # Timestamp
    # ==========================================

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    elements.append(
        Paragraph(
            f"<b>Generated:</b> {timestamp}",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1,10)
    )

    # ==========================================
    # Prediction
    # ==========================================

    elements.append(
        Paragraph(
            f"<b>Prediction:</b> {prediction}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f}%",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1,20)
    )

    # ==========================================
    # Report
    # ==========================================

    elements.append(
        Paragraph(
            "<b>Clinical Analysis</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1,10)
    )

    report_text = report_text.replace(
        "\n",
        "<br/>"
    )

    elements.append(
        Paragraph(
            report_text,
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1,20)
    )

    # ==========================================
    # Footer
    # ==========================================

    disclaimer = """
    <b>Disclaimer:</b><br/>
    This report was generated by a research prototype.
    It is intended for educational, research, and
    demonstration purposes only and must not be used
    as a substitute for professional medical diagnosis.
    """

    elements.append(
        Paragraph(
            disclaimer,
            styles["Italic"]
        )
    )

    doc.build(elements)

    return filename

pdf_path = create_pdf_report(
    prediction=result["prediction"],
    confidence=result["confidence"],
    report_text=result["report"]
)

print("PDF Generated:", pdf_path)

import os

print(
    os.path.exists(
        "Brain_MRI_Report.pdf"
    )
)

from google.colab import files

files.download(
    "Brain_MRI_Report.pdf"
)

!pip install gradio grad-cam reportlab -q

import os

os.makedirs("MedVision_Brain", exist_ok=True)

print("Project Folder Created")

requirements = """
torch
torchvision
numpy
opencv-python
Pillow
matplotlib
gradio
grad-cam
reportlab
"""

with open("requirements.txt","w") as f:
    f.write(requirements)

print("requirements.txt created")

!pip install -q gradio

